### ISSUE TITLE
Commits seem to be slower again after update of AuthorizationCache

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#63]
Commits, eg while forking objects in ObjectHub seem to be slower again ...

**Comment by objecthub-io** [comment]
To Fix: Authorization Cache stores a lot of extra 'read' tokens - these must not be stored, if the node was authorized from cache.

**Comment by stellardb** [comment]
This did not seem to be the issue. The issue was frequent server restarts - this is fixed now.
