### ISSUE TITLE
CreateDatabaseIfNotExists returns with success but database does not exist.

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#67]
After calling `Databases.at(...).createIfNotExists()` this call returns with a success - but when trying to access the database afterwards, it issues a No Node Defined at Address warning.

First encountered with a Database object for which the `~d` database cannot be accessed.

**Comment by objecthub-io** [comment]
It seems while a database with the id `d` exists for the node, no node exists as the root node for this database.

**Comment by objecthub-io** [comment]
Might have been caused by frequent server restarts/crashes?

**Comment by stellardb** [comment]
Does not seem to happen anymore.
