### ISSUE TITLE
Log file not created correctly

### ISSUE THREAD

**Issue by stellardb** [stellardb/StellarDB#75]
Sometimes production.log is not created correctly after using logrotate.

**Comment by objecthub-io** [comment]
When running logroate with `--force` the server is restarted correctly and production.txt is used as the log file.

However, when it did the last weekly rotation, it did not seem to have worked correctly. The application was logging into production.txt.1.

**Comment by stellardb** [comment]
No issue. Just get latest log data from production.txt.1.
