### ISSUE TITLE
Server hangs

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#79]
Reported during deleting of production database in Micro Services.

Still works:

- GWT RPC.
- https://objecthub.io/admin/metrics/main.json
- Access databases using Java API
- Accessing https://r1.objecthub.io/objects
- Accessing https://u1.objecthub.io/objecthub

Does not work:

- objecthub.io
- Access of nodes via REST interface
- Download a single node via Java API from objecthub.io

**Comment by mxro** [comment]
Also see #71

**Comment by mxro** [comment]
Seems to be causes by crash of objecthub.io node network server.

**Comment by mxro** [comment]
Another issue of hanging occurred for the Database Management Processor.

Here specifically after a new user was created, the usage charges for this user were not displayed.

This was caused by GetDatabaseSize messages not being processed.

**Comment by stellardb** [comment]
Fixed how SequentialOperationsScheduler handles failures and made more schedulers to use their own threads.

**Comment by stellardb** [comment]
Does not seem to appear anymore.
