### ISSUE TITLE
select(type) not immediately resolved

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#89]
When selecting and setting value in one operation such as:

```
db.root().select(Time).setValue(input.time);
db.root().select(Distance).setValue(input.distance);

client.commit()...
```

Where `Time` and `Distance` are nodes, the values of the nodes is not set after a commit.

It works however, when using paths to select the nodes to change:

```
db.root().select("./time").setValue(input.time);
db.root().select("./distance").setValue(input.distance);
```

**Comment by stellardb** [comment]
Fixed.

Caused by EagerOperationsCache not waiting for all runSafe() operations of client completed.
